import 'package:flutter/material.dart';

import '../huf_border_radius.dart';
import '../huf_glow.dart';
import '../huf_theme_palette.dart';
import '../huf_theme_colors.dart';
import '../huf_theme_preset.dart';

/// Bundle di token per un tema predefinito HeroUI.
@immutable
class HUFThemePresetBundle {
  const HUFThemePresetBundle({
    this.light,
    this.dark,
    this.borderRadius,
    this.glowSize,
  });

  final HUFThemePalette? light;
  final HUFThemePalette? dark;
  final HUFBorderRadius? borderRadius;
  final HUFGlowSize? glowSize;
}

/// Temi predefiniti HeroUI (convertiti da OKLCH `@heroui/styles`).
abstract final class HUFThemePresets {
  HUFThemePresets._();

  static const HUFThemePresetBundle defaultTheme = HUFThemePresetBundle();

  static const HUFThemePresetBundle sky = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF4F5F6),
              border: Color(0xFFDDDEDF),
              primary: Color(0xFF00CBFF),
              primaryForeground: Color(0xFF000E15),
              secondary: Color(0xFFEAEBEC),
              secondaryForeground: Color(0xFF16191A),
              danger: Color(0xFFFF3549),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFFFFE8EB),
              dangerSoftForeground: Color(0xFFC2001A),
              success: Color(0xFF36C85A),
              successForeground: Color(0xFF171917),
              warning: Color(0xFFF9A22A),
              warningForeground: Color(0xFF1A1815),
              disabled: Color(0xFFEAEBEC),
              disabledForeground: Color(0xFF707273),
              transparent: Color(0x00000000),
              card: Color(0xFFFEFFFF),
              cardSecondary: Color(0xFFEEEFF0),
              cardTertiary: Color(0xFFE9EAEB),
              cardForeground: Color(0xFF181819),
              cardMutedForeground: Color(0xFF707273),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF050606),
              border: Color(0xFF282929),
              primary: Color(0xFF00CBFF),
              primaryForeground: Color(0xFF000E15),
              secondary: Color(0xFF272728),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFDB3947),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFF3A1A1D),
              dangerSoftForeground: Color(0xFFFF8A93),
              success: Color(0xFF36C85A),
              successForeground: Color(0xFF171917),
              warning: Color(0xFFFBB552),
              warningForeground: Color(0xFF1A1815),
              disabled: Color(0xFF272728),
              disabledForeground: Color(0xFF9EA0A1),
              transparent: Color(0x00000000),
              card: Color(0xFF171919),
              cardSecondary: Color(0xFF222324),
              cardTertiary: Color(0xFF262728),
              cardForeground: Color(0xFFFBFCFD),
              cardMutedForeground: Color(0xFF9EA0A1),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle lavender = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF5F5F6),
              border: Color(0xFFDEDEDF),
              primary: Color(0xFFC79EF7),
              primaryForeground: Color(0xFF0E0814),
              secondary: Color(0xFFEBEBEC),
              secondaryForeground: Color(0xFF19181B),
              danger: Color(0xFFFF3C1C),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFFFFE5E0),
              dangerSoftForeground: Color(0xFFC21A00),
              success: Color(0xFF00CB74),
              successForeground: Color(0xFF161917),
              warning: Color(0xFFEEA915),
              warningForeground: Color(0xFF1A1815),
              disabled: Color(0xFFEBEBEC),
              disabledForeground: Color(0xFF727273),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFF0),
              cardTertiary: Color(0xFFEAEAEB),
              cardForeground: Color(0xFF191819),
              cardMutedForeground: Color(0xFF727273),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF060606),
              border: Color(0xFF292929),
              primary: Color(0xFFC79EF7),
              primaryForeground: Color(0xFF0E0814),
              secondary: Color(0xFF272728),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFDB3E29),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFF3A1E1A),
              dangerSoftForeground: Color(0xFFFF9A8A),
              success: Color(0xFF00CB74),
              successForeground: Color(0xFF161917),
              warning: Color(0xFFF0BB4C),
              warningForeground: Color(0xFF1A1815),
              disabled: Color(0xFF272728),
              disabledForeground: Color(0xFFA09FA1),
              transparent: Color(0x00000000),
              card: Color(0xFF191819),
              cardSecondary: Color(0xFF232324),
              cardTertiary: Color(0xFF272728),
              cardForeground: Color(0xFFFCFCFD),
              cardMutedForeground: Color(0xFFA09FA1),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle mint = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF4F5F5),
              border: Color(0xFFDDDEDD),
              primary: Color(0xFF80DBA2),
              primaryForeground: Color(0xFF040E07),
              secondary: Color(0xFFEAEBEB),
              secondaryForeground: Color(0xFF161917),
              danger: Color(0xFFFD3364),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFFFFE5EB),
              dangerSoftForeground: Color(0xFFC2003A),
              success: Color(0xFF60C43E),
              successForeground: Color(0xFF171916),
              warning: Color(0xFFFF9D3C),
              warningForeground: Color(0xFF1A1816),
              disabled: Color(0xFFEAEBEB),
              disabledForeground: Color(0xFF717271),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFEF),
              cardTertiary: Color(0xFFEAEAEA),
              cardForeground: Color(0xFF181918),
              cardMutedForeground: Color(0xFF717271),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF050606),
              border: Color(0xFF282928),
              primary: Color(0xFF80DBA2),
              primaryForeground: Color(0xFF040E07),
              secondary: Color(0xFF272827),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFD9385D),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFF3A1A22),
              dangerSoftForeground: Color(0xFFFF8AA5),
              success: Color(0xFF60C43E),
              successForeground: Color(0xFF171916),
              warning: Color(0xFFFFB05B),
              warningForeground: Color(0xFF1A1816),
              disabled: Color(0xFF272827),
              disabledForeground: Color(0xFF9EA09F),
              transparent: Color(0x00000000),
              card: Color(0xFF171918),
              cardSecondary: Color(0xFF222423),
              cardTertiary: Color(0xFF262726),
              cardForeground: Color(0xFFFBFCFC),
              cardMutedForeground: Color(0xFF9EA09F),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle netflix = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF5F5F5),
              border: Color(0xFFDEDEDE),
              primary: Color(0xFFE50914),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFFEBEBEB),
              secondaryForeground: Color(0xFF1B1717),
              danger: Color(0xFFB20710),
              dangerForeground: Color(0xFFFFF4F1),
              dangerSoft: Color(0xFFFFE8E9),
              dangerSoftForeground: Color(0xFFB20710),
              success: Color(0xFF237B35),
              successForeground: Color(0xFFF3FBF3),
              warning: Color(0xFF996B00),
              warningForeground: Color(0xFFFDF8F0),
              disabled: Color(0xFFEBEBEB),
              disabledForeground: Color(0xFF727272),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFEF),
              cardTertiary: Color(0xFFEAEAEA),
              cardForeground: Color(0xFF181818),
              cardMutedForeground: Color(0xFF727272),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF060606),
              border: Color(0xFF292929),
              primary: Color(0xFFE50914),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFF272727),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFB9090B),
              dangerForeground: Color(0xFFFFF4F1),
              dangerSoft: Color(0xFF3A1214),
              dangerSoftForeground: Color(0xFFFF9A9C),
              success: Color(0xFF46D369),
              successForeground: Color(0xFF001001),
              warning: Color(0xFFFFB53F),
              warningForeground: Color(0xFF160700),
              disabled: Color(0xFF272727),
              disabledForeground: Color(0xFFA0A0A0),
              transparent: Color(0x00000000),
              card: Color(0xFF181818),
              cardSecondary: Color(0xFF232323),
              cardTertiary: Color(0xFF272727),
              cardForeground: Color(0xFFFCFCFC),
              cardMutedForeground: Color(0xFFA0A0A0),
            ),
          ),
          borderRadius: HUFBorderRadius.extraSmall,
  );

  static const HUFThemePresetBundle uber = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF5F5F5),
              border: Color(0xFFDEDEDE),
              primary: Color(0xFF000000),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFFEBEBEB),
              secondaryForeground: Color(0xFF1B1718),
              danger: Color(0xFFDE1135),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFFFFE8EC),
              dangerSoftForeground: Color(0xFFDE1135),
              success: Color(0xFF05A357),
              successForeground: Color(0xFFF1FCF3),
              warning: Color(0xFFFFC043),
              warningForeground: Color(0xFF150800),
              disabled: Color(0xFFEBEBEB),
              disabledForeground: Color(0xFF727272),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFEF),
              cardTertiary: Color(0xFFEAEAEA),
              cardForeground: Color(0xFF181818),
              cardMutedForeground: Color(0xFF727272),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF060606),
              border: Color(0xFF292929),
              primary: Color(0xFFFAFAFA),
              primaryForeground: Color(0xFF0B0B0B),
              secondary: Color(0xFF272727),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFFF6666),
              dangerForeground: Color(0xFF1C0203),
              dangerSoft: Color(0xFF3A1A1C),
              dangerSoftForeground: Color(0xFFFFAAAA),
              success: Color(0xFF3AA76D),
              successForeground: Color(0xFF001005),
              warning: Color(0xFFFFD166),
              warningForeground: Color(0xFF130900),
              disabled: Color(0xFF272727),
              disabledForeground: Color(0xFFA0A0A0),
              transparent: Color(0x00000000),
              card: Color(0xFF181818),
              cardSecondary: Color(0xFF232323),
              cardTertiary: Color(0xFF272727),
              cardForeground: Color(0xFFFCFCFC),
              cardMutedForeground: Color(0xFFA0A0A0),
            ),
          ),
          borderRadius: HUFBorderRadius.small,
  );

  static const HUFThemePresetBundle spotify = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF4F5F4),
              border: Color(0xFFDDDEDD),
              primary: Color(0xFF1ED760),
              primaryForeground: Color(0xFF030F05),
              secondary: Color(0xFFEAEBEA),
              secondaryForeground: Color(0xFF171917),
              danger: Color(0xFFD31225),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFFFFE8EA),
              dangerSoftForeground: Color(0xFFD31225),
              success: Color(0xFF169C46),
              successForeground: Color(0xFFF1FCF2),
              warning: Color(0xFFEB7B15),
              warningForeground: Color(0xFF1A0400),
              disabled: Color(0xFFEAEBEA),
              disabledForeground: Color(0xFF707371),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEEEFEF),
              cardTertiary: Color(0xFFE9EAEA),
              cardForeground: Color(0xFF181918),
              cardMutedForeground: Color(0xFF707371),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF050605),
              border: Color(0xFF282928),
              primary: Color(0xFF1ED760),
              primaryForeground: Color(0xFF030F05),
              secondary: Color(0xFF272827),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFE91429),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFF3A1216),
              dangerSoftForeground: Color(0xFFFF8A95),
              success: Color(0xFF1ED760),
              successForeground: Color(0xFF001001),
              warning: Color(0xFFFFA42B),
              warningForeground: Color(0xFF180600),
              disabled: Color(0xFF272827),
              disabledForeground: Color(0xFF9EA19E),
              transparent: Color(0x00000000),
              card: Color(0xFF171917),
              cardSecondary: Color(0xFF222422),
              cardTertiary: Color(0xFF262726),
              cardForeground: Color(0xFFFBFCFB),
              cardMutedForeground: Color(0xFF9EA19E),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle coinbase = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF4F5F6),
              border: Color(0xFFDDDEDF),
              primary: Color(0xFF0052FF),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFFEAEBEC),
              secondaryForeground: Color(0xFF17181B),
              danger: Color(0xFFCF202F),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFFFFE8EA),
              dangerSoftForeground: Color(0xFFCF202F),
              success: Color(0xFF098551),
              successForeground: Color(0xFFF2FBF5),
              warning: Color(0xFFF5B073),
              warningForeground: Color(0xFF150700),
              disabled: Color(0xFFEAEBEC),
              disabledForeground: Color(0xFF717274),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFF0),
              cardTertiary: Color(0xFFEAEAEB),
              cardForeground: Color(0xFF181819),
              cardMutedForeground: Color(0xFF717274),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF050606),
              border: Color(0xFF28292A),
              primary: Color(0xFF0052FF),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFF272728),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFF84550),
              dangerForeground: Color(0xFF1C0203),
              dangerSoft: Color(0xFF3A1A1C),
              dangerSoftForeground: Color(0xFFFF9AA0),
              success: Color(0xFF00D180),
              successForeground: Color(0xFF001104),
              warning: Color(0xFFF5B073),
              warningForeground: Color(0xFF150700),
              disabled: Color(0xFF272728),
              disabledForeground: Color(0xFF9EA0A2),
              transparent: Color(0x00000000),
              card: Color(0xFF17181A),
              cardSecondary: Color(0xFF222325),
              cardTertiary: Color(0xFF262728),
              cardForeground: Color(0xFFFBFCFD),
              cardMutedForeground: Color(0xFF9EA0A2),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle airbnb = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF5F5F5),
              border: Color(0xFFDEDEDE),
              primary: Color(0xFFFF385C),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFFEBEBEB),
              secondaryForeground: Color(0xFF1B1717),
              danger: Color(0xFFC13515),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFFFFE8E4),
              dangerSoftForeground: Color(0xFFC13515),
              success: Color(0xFF008489),
              successForeground: Color(0xFFFCFCFC),
              warning: Color(0xFFFC642D),
              warningForeground: Color(0xFFFCFCFC),
              disabled: Color(0xFFEBEBEB),
              disabledForeground: Color(0xFF727272),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFFFF),
              cardSecondary: Color(0xFFEFEFEF),
              cardTertiary: Color(0xFFEAEAEA),
              cardForeground: Color(0xFF181818),
              cardMutedForeground: Color(0xFF727272),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF060606),
              border: Color(0xFF292929),
              primary: Color(0xFFFF385C),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFF272727),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFC13515),
              dangerForeground: Color(0xFFFCFCFC),
              dangerSoft: Color(0xFF3A1A14),
              dangerSoftForeground: Color(0xFFFF9A7A),
              success: Color(0xFF00A699),
              successForeground: Color(0xFFFCFCFC),
              warning: Color(0xFFFFB400),
              warningForeground: Color(0xFF160700),
              disabled: Color(0xFF272727),
              disabledForeground: Color(0xFFA0A0A0),
              transparent: Color(0x00000000),
              card: Color(0xFF181818),
              cardSecondary: Color(0xFF232323),
              cardTertiary: Color(0xFF272727),
              cardForeground: Color(0xFFFCFCFC),
              cardMutedForeground: Color(0xFFA0A0A0),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static const HUFThemePresetBundle discord = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFF3F5FC),
              border: Color(0xFFDCDEE5),
              primary: Color(0xFF5865F2),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFFE9EBF2),
              secondaryForeground: Color(0xFF17181B),
              danger: Color(0xFFDA373C),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFFFFE8E9),
              dangerSoftForeground: Color(0xFFDA373C),
              success: Color(0xFF248046),
              successForeground: Color(0xFFF3FBF4),
              warning: Color(0xFFFEE75C),
              warningForeground: Color(0xFF100B00),
              disabled: Color(0xFFE9EBF2),
              disabledForeground: Color(0xFF6E717E),
              transparent: Color(0x00000000),
              card: Color(0xFFFEFFFF),
              cardSecondary: Color(0xFFEDEFF5),
              cardTertiary: Color(0xFFE8EAF0),
              cardForeground: Color(0xFF17181D),
              cardMutedForeground: Color(0xFF6E717E),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF050609),
              border: Color(0xFF27292E),
              primary: Color(0xFF5865F2),
              primaryForeground: Color(0xFFFCFCFC),
              secondary: Color(0xFF26272C),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFED4245),
              dangerForeground: Color(0xFFFFF4F2),
              dangerSoft: Color(0xFF3A1A1C),
              dangerSoftForeground: Color(0xFFFF8A8D),
              success: Color(0xFF57F287),
              successForeground: Color(0xFF001002),
              warning: Color(0xFFFEE75C),
              warningForeground: Color(0xFF100B00),
              disabled: Color(0xFF26272C),
              disabledForeground: Color(0xFF9C9FAD),
              transparent: Color(0x00000000),
              card: Color(0xFF151822),
              cardSecondary: Color(0xFF21232B),
              cardTertiary: Color(0xFF24272E),
              cardForeground: Color(0xFFFAFCFF),
              cardMutedForeground: Color(0xFF9C9FAD),
            ),
          ),
          borderRadius: HUFBorderRadius.small,
  );

  static const HUFThemePresetBundle rabbit = HUFThemePresetBundle(
    light: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFFFCF3F0),
              border: Color(0xFFE4DCD9),
              primary: Color(0xFFFF4D06),
              primaryForeground: Color(0xFF160704),
              secondary: Color(0xFFF2E9E6),
              secondaryForeground: Color(0xFF1B1716),
              danger: Color(0xFFFF0606),
              dangerForeground: Color(0xFFFFF4F1),
              dangerSoft: Color(0xFFFFE5E5),
              dangerSoftForeground: Color(0xFFFF0606),
              success: Color(0xFF4ABF34),
              successForeground: Color(0xFF011000),
              warning: Color(0xFFFF9357),
              warningForeground: Color(0xFF1B1816),
              disabled: Color(0xFFF2E9E6),
              disabledForeground: Color(0xFF7D6E6A),
              transparent: Color(0x00000000),
              card: Color(0xFFFFFEFD),
              cardSecondary: Color(0xFFF4EDEB),
              cardTertiary: Color(0xFFEFE8E6),
              cardForeground: Color(0xFF1D1715),
              cardMutedForeground: Color(0xFF7D6E6A),
            ),
          ),
          dark: const HUFThemePalette(
            colors: HUFThemeColors(
              background: Color(0xFF090504),
              border: Color(0xFF2E2725),
              primary: Color(0xFFFF4D06),
              primaryForeground: Color(0xFF160704),
              secondary: Color(0xFF2C2624),
              secondaryForeground: Color(0xFFFCFCFC),
              danger: Color(0xFFFF0606),
              dangerForeground: Color(0xFFFFF4F1),
              dangerSoft: Color(0xFF3A1414),
              dangerSoftForeground: Color(0xFFFF8A8A),
              success: Color(0xFF4ABF34),
              successForeground: Color(0xFF011000),
              warning: Color(0xFFFFA76C),
              warningForeground: Color(0xFF1B1816),
              disabled: Color(0xFF2C2624),
              disabledForeground: Color(0xFFAC9C97),
              transparent: Color(0x00000000),
              card: Color(0xFF211512),
              cardSecondary: Color(0xFF2A211E),
              cardTertiary: Color(0xFF2E2422),
              cardForeground: Color(0xFFFFFAF7),
              cardMutedForeground: Color(0xFFAC9C97),
            ),
          ),
          borderRadius: const HUFBorderRadius(value: 8),
  );

  static HUFThemePresetBundle forPreset(HUFThemePreset preset) => switch (preset) {
        HUFThemePreset.defaultTheme => defaultTheme,
        HUFThemePreset.sky => sky,
        HUFThemePreset.lavender => lavender,
        HUFThemePreset.mint => mint,
        HUFThemePreset.netflix => netflix,
        HUFThemePreset.uber => uber,
        HUFThemePreset.spotify => spotify,
        HUFThemePreset.coinbase => coinbase,
        HUFThemePreset.airbnb => airbnb,
        HUFThemePreset.discord => discord,
        HUFThemePreset.rabbit => rabbit,
      };
}

